config/routes.rb
Summit2012Kt::Application.routes.draw do
  root :to => 'articles#index'
  resources :categories
  resources :articles
  get "pages/index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_and_belongs_to_many :categories
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles

  def full_name
    " #{last_name}, #{first_name} "
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_categories

  def get_categories
    @categories = Category.all
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :get_authors, only: [:new, :edit]

  def get_authors
    @authors = Author.all
  end
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    categories = Category.find(params[:category_ids]) if params[:category_ids]
    @article.categories.concat categories if categories  

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    categories = Category.find(params[:category_ids]) if params[:category_ids]
    @article.categories.clear 
    @article.categories.concat categories if categories  

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_category.html.erb
<%= check_box_tag 'category_ids[]', category.id, @article.categories.include?(category)  %>
<%= h category.name if category %>
 

app/views/articles/_category_display.html.erb
<ul>
  <% categories.each do |category| %>
    <li><%= category.name %></li> 
  <% end %>
</ul>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= label_tag "Author" %><br />
      <%= collection_select(:article, :author_id, @authors, :id, :full_name, prompt: true)  %> </div>
    <div class="field">
      <%= label_tag "Select category" %><br /> 
      <% #@categories.each do |category| %>
<% #check_box_tag 'category_ids[]', category.id, @article.categories.include?(category) %>
<% #h category.name %>
    <%= render partial: 'category', collection: @categories %>
    <% # end %>
    </div>
    <br />
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2 class="alt">Editing article</h2>

<%= render 'form' %>

<%= link_to 'Show', @article, class: "button" %> 
<%= link_to 'Back', articles_path, class: "button" %>

app/views/articles/index.html.erb
<h2 class="alt">Listing articles</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Author</th>
    <th>Categories</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.body %></td>
    <td><%= article.author.full_name if article.author %></td>
    <td>
      <%= render partial: "category_display", locals: { categories: article.categories } %>
     </td>
    <td><%= link_to 'Show', article, class: "button" %></td>
    <td><%= link_to 'Edit', edit_article_path(article), class: "button" %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete, class: "button" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path, class: "button" %>

app/views/articles/new.html.erb
<h2 class="alt">New article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "button" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <b>Title:</b>
  <%= @article.title %>
</div>

<div>
  <b>Body:</b>
  <%= @article.body %>
</div>

<div>
  <b>Author:</b>
  <%= @article.author.full_name %>
</div>
<div>
 <b>Categories:</b>
 <%= render partial: "category_display", locals: { categories: @article.categories } %>
     </div>


<%= link_to 'Edit', edit_article_path(@article), class: "button" %> 
<%= link_to 'Back', articles_path, class: "button" %>

app/views/categories/_category.html.erb
  <%= category.name  %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category , class: "button" %> 
<%= link_to 'Back', categories_path , class: "button" %>

app/views/categories/index.html.erb
<h2 class="alt">Listing categories</h2>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category, class: "button" %></td>
    <td><%= link_to 'Edit', edit_category_path(category) , class: "button" %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete , class: "button" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path , class: "button" %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path , class: "button" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) , class: "button" %> 
<%= link_to 'Back', categories_path , class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Summit2012Kt</title>
  <%= stylesheet_link_tag    "blueprint/screen", media: "screen, projection" %>
  <%= stylesheet_link_tag    "blueprint/print", media: "print" %>
  <!--[if lt IE 8]>
  <%= stylesheet_link_tag    "blueprint/ie", media: "screen, projection" %>
  <![endif]-->
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="darkblue">
  <div class="wrapper">
    <div class="container ">
      <div class="span-24 last prepend-top">
        <h1> Test App to build summit exercises </h1>
      </div>
    </div>
  </div>
  <div class="container prepend-top">
  <div class="span-17 border"  >
    <%= yield %>
  </div>
  <div class="span-6 box last"> 
    <h2 class="alt">Categories</h2> 
    <%= render @categories  %></div>
  <div class="span-24 bottom last" > footer </div>
</div>
</body>
</html>

app/views/pages/_category.html.erb
<h2 class="alt">Categories</h2>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/index.html.erb
<h2 class="alt">Pages#index</h2>
<p>Find me in app/views/pages/index.html.erb</p>